In [ ]:
# import lib
import pandas as pd 
import gspread  # import lib để ... key 
from oauth2client.service_account import ServiceAccountCredentials # giúp python hiểu credential là gì
from sqlalchemy import create_engine    
import calendar
from datetime import datetime, timedelta
import math 
import numpy as np
pd.options.mode.chained_assignment = None # ignore SettingWithCopyWarning in Pandas

In [ ]:
# set up credential
json_credential = {
  "type": "service_account",
  "project_id": "schfe-370303",
  "private_key_id": "f5a275c336c281486ca54e4252cf7c0c738212fd",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC/P/LQtXI73PWF\ne6OzqlrKMeXm5t3AEzIWLvD/OIMHT53mFrKW4CmHLI0UAGIEhu47mhKYLqqUDFG4\nhcf35tgdnQ/aH2+vk++xw03uXcaKcBmtC0fxEWIvR5/o6D56WmJo0as7Jg07W508\nwcX8xKaGP59ffCuYpQD748z/cGYM2Rhea6JsYEK4ScHKdnYCqJc7k9dlLzWJrIys\n/jdJnDDUKeeGq8n0xoLupxkEqcF1B0tpSzOuffxNlmPYy7JS5L8iL48qgRerxUP4\nonmGNnGv5cV8OdalApyqN5bTGR59F6AkpbOo6rsLzoTS/xk9d0IiRehuuGwO7MrN\nq3m+fnVlAgMBAAECggEAAQ7O/oWKaLdbqk3ZRXSjROwKvAC56EaS59mBnr/GxcMU\negHVIg2CXUuLSjmIUUMXzT+Ya7wSWHhK+WzQAtiFiIBmZov2968nS8HrS+672ucs\n1S6zSquQcfeA9G5Ybh/S3IaQXmbi+tmSYJQnzrKdwy9V59bNfO4ot7v2VdFe1yJX\n0+dQyuTtxYzG2NXp8Cmuxry5bmPNDyqgTlatsHTRBVtTdyPx4Id4UDGFbv2AINlx\nsOmktdsjtwVJDDxSu7AmmlNrcvhV3lR0GdSoTqHHbvxTViswid7KnDLDcYr3pxaq\n7+kad0bEDx1VfsPPBd8NA5x5y35pazPLtRpnu81xYQKBgQDhoYLg5ezFe/48ROtd\nLie86sqrLgJuvpEvl/yLy184iSkVAZrMqSYXyeDnH5ptJqkjrjdDRs925RcgkKdx\n2Jxy2m9JpD1VczRQ540xX9LECqoYuTu/y7oPpWl0G/UsQVuOcgKXSZdEjVN035GJ\nhK2FCEXkWFvtiqZ9EpfCdrIo9QKBgQDY/cds/Ds6g5ZzyYITerrOA3SpfJKBm6j6\nPOsNNSREy0mv8HkkghzSfNBYX/yH9xmf4xhxScYhA4JkdW4SkPaGjw/g98NX0fBW\nFozi9T9DLKRRqkG9HkI1dNQJyCb8bw+8i2n+y+sPeOgYAKGeEmyZrUBY2op1m8f0\n0fL+G4kUsQKBgEzGRF56XiKkmlGvsda3CdaCngu5UCKWvZhQQyLeRLxcD5qSPTY+\nqDOYAesjGcziRtNZSHyf76ApO8Fc910Js9Jw+UU5mZUl6jtNTwHp9TG330EiZm5Q\nyDLiugtEKByy8JB7wt3vsIUnAarXGBKPDuwhcIbOehlOAHC2juUgtmaxAoGBANau\nJcretZ6Lp6OAnu+0wfKmmppAhBY0sfZ5pLeZdvuVAJ9P1BrZm7hoAh0dQhQm1bRJ\nEtqqeZoaBbxsLe2yfCTej4AswJg3PYd+of69Usyb8ypUvttjf2+x2UKgQmoHW1NX\nvxN2HmZdYYq1vTBN3CIitYHzHX+EE01VFgpvpazRAoGACPaiS4kBeusvidxULTZN\nWzKpIlBSyz2q4q3SnHeqysraFoBz22HBuVKMuxXAtIEyeNvRBZwswEqGnp+nIS8B\nhjAysNhQ8U2llzO8bKqKOsiPJC0y4YOpPeuX0U4259sxYZXKSDIht/NKi+uoAmn4\n5bi21TtWT7us7DdVRlYl+ao=\n-----END PRIVATE KEY-----\n",
  "client_email": "schackfest@schfe-370303.iam.gserviceaccount.com",
  "client_id": "117174207875746908121",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/schackfest%40schfe-370303.iam.gserviceaccount.com"
}

# Load credential
scope = ['https://spreadsheets.google.com/feeds'] 
credentials = ServiceAccountCredentials.from_json_keyfile_dict(json_credential, scope) 
gc = gspread.authorize(credentials)

In [ ]:
# DEMAND ĐÔNG NAM BỘ
# Select sheet Đông Nam Bộ
sheet_demand_dnb = gc.open_by_url('https://docs.google.com/spreadsheets/d/16ABL8ArggCsUlfHr9Kx3hQElvmHi2yQUXBIhpS9O1aw/edit#gid=0').worksheet('Đông Nam Bộ')

# Select All columns
data = [e[0:] for e in sheet_demand_dnb.get_all_values()] 

# Set first row of sheet as Dataframe column name
df_demand_dnb = pd.DataFrame(data[0:], columns=data[0]) # Check
df_demand_dnb = df_demand_dnb.drop(df_demand_dnb.index[0])
df_demand_dnb['APR_2023'] = df_demand_dnb['APR_2023'].astype('float64')
df_demand_dnb['MAY_2023'] = df_demand_dnb['MAY_2023'].astype('float64')
df_demand_dnb['JUN_2023'] = df_demand_dnb['JUN_2023'].astype('float64')

# SOH ĐÔNG NAM BỘ
df_soh_dnb = gc.open_by_url('https://docs.google.com/spreadsheets/d/1CbcVBSIXpGeFG_5BeN_o6Jna33WN0lWRCDP-6PBDa-A/edit#gid=0').worksheet('Đông Nam Bộ')
# Select All columns
data = [e[0:] for e in df_soh_dnb.get_all_values()] 
# Set first row of sheet as Dataframe column name
df_soh_dnb = pd.DataFrame(data[0:], columns=data[0]) # Check
df_soh_dnb = df_soh_dnb.drop(df_soh_dnb.index[0])
df_soh_dnb["TỒN KHO CUỐI NGÀY 31/3/2023"] = df_soh_dnb["TỒN KHO CUỐI NGÀY 31/3/2023"].astype('float64')

# production required - only change the demand of APR
# production required - only change the demand of APR
for ind, data in df_soh_dnb.iterrows():
  xx = df_soh_dnb.loc[ind,"ITEM"]
  if xx == "STAR_SHEEP_25KG":
    x = df_soh_dnb.loc[ind,"TỒN KHO CUỐI NGÀY 31/3/2023"]
    indd = df_demand_dnb.loc[df_demand_dnb["ITEM"] == "STAR_SHEEP_25KG"].index
    df_demand_dnb.loc[indd,"APR_2023"] = df_demand_dnb.loc[indd,"APR_2023"] - x
    df_soh_dnb = df_soh_dnb.drop(axis = 0, index = ind)
    continue
  if xx == "STAR_SHEEP_40KG":
    x = df_soh_dnb.loc[ind,"TỒN KHO CUỐI NGÀY 31/3/2023"]
    indd = df_demand_dnb.loc[df_demand_dnb["ITEM"] == "STAR_SHEEP_40KG"].index
    df_demand_dnb.loc[indd,"APR_2023"] = df_demand_dnb.loc[indd,"APR_2023"] - x
    df_soh_dnb = df_soh_dnb.drop(axis = 0, index = ind)
    continue
  if xx == "WOW_CHICKEN_25KG":
    x = df_soh_dnb.loc[ind,"TỒN KHO CUỐI NGÀY 31/3/2023"]
    indd = df_demand_dnb.loc[df_demand_dnb["ITEM"] == "WOW_CHICKEN_25KG"].index
    df_demand_dnb.loc[indd,"APR_2023"] = df_demand_dnb.loc[indd,"APR_2023"] - x
    df_soh_dnb = df_soh_dnb.drop(axis = 0, index = ind)
    continue
  if xx == "WOW_CHICKEN_40KG":
    x = df_soh_dnb.loc[ind,"TỒN KHO CUỐI NGÀY 31/3/2023"]
    indd = df_demand_dnb.loc[df_demand_dnb["ITEM"] == "WOW_CHICKEN_40KG"].index
    df_demand_dnb.loc[indd,"APR_2023"] = df_demand_dnb.loc[indd,"APR_2023"] - x
    df_soh_dnb = df_soh_dnb.drop(axis = 0, index = ind)
    continue

df_demand_dnb = df_demand_dnb.set_index('ITEM')
print(df_demand_dnb)

                  APR_2023  MAY_2023  JUN_2023
ITEM
STAR_SHEEP_25KG      124.0     300.0     350.0
STAR_SHEEP_40KG       90.0     250.0     200.0
WOW_CHICKEN_25KG     438.0     700.0     850.0
WOW_CHICKEN_40KG     100.0     200.0     250.0

In [ ]:
# tạo 1 dictionary gồm tháng có demand forecast & tổng số ngày trong tháng đó (bao gồm Chủ Nhật)
date_list = []
eomonth_list = []


for ind,data in enumerate(df_demand_dnb.columns):
    date_list.append(datetime.strptime(data,'%b_%Y')) # append column heading as date into a list
    
    eomonth_list.append(calendar.monthrange(datetime.strptime(data,'%b_%Y').year,datetime.strptime(data,'%b_%Y').month)[1]) # find the last day of each month

month_eomonth = {date_list[i]:eomonth_list[i] for i in range(len(date_list))} # create a list of each month & its last day

# tạo 1 list ngày làm việc của Festory theo từng tháng (ngày trong tháng trừ Chủ Nhật)
date_exclude_Sun = []
for date,eomonth in month_eomonth.items():
    day = 1 # gán biến chạy là ngày đầu tiên hàng tháng
    while day <= eomonth: # make sure ngày có trong tháng 
        if datetime(date.year,date.month,day).weekday() != 6: # filter ngày chủ nhật
            date_exclude_Sun.append(datetime(date.year,date.month,day)) # add các ngày thỏa điều kiện vào 1 list
        day += 1
    continue

# tính TỔNG số ngày làm việc (working_day) của Festory theo từng tháng (ngày trong tháng trừ Chủ Nhật)

total_apr = total_may = total_jun = 0

for i in date_exclude_Sun:
    if i.month == 4:
        total_apr += 1 
    elif i.month == 5:
        total_may += 1
    else:
        total_jun += 1

total_day = [total_apr,total_may,total_jun]
working_day = {date_list[i].month:total_day[i] for i in range(len(date_list))}

# round up Daily_Demand to one decimal
def round_up(num):
    return math.ceil(num * 10) / 10

date_month = []
last_day = []

for d, l in month_eomonth.items():
    date_month.append(d.month)
    last_day.append(l)
    
month_n_last_day = {date_month[i]:last_day[i] for i in range(len(date_month))}

In [ ]:
# tạo  1 empty df với col headings
df_daily_demand_dnb = pd.DataFrame(columns=['DATE', 'THÀNH PHẨM', 'MONTHLY_DEMAND_QTY', 'daily_demand']) 
df_daily_demand_dnb = df_daily_demand_dnb.set_index('DATE')


# round up Daily_Demand to one decimal
def round_up(num):
    return math.ceil(num * 10) / 10

date_month = []
last_day = []

for d, l in month_eomonth.items():
    date_month.append(d.month)
    last_day.append(l)
    
month_n_last_day = {date_month[i]:last_day[i] for i in range(len(date_month))}

for ind,dt in enumerate(date_exclude_Sun):
    col = datetime.strftime(dt,'%b_%Y').upper() # chuyển datetime to str để so sánh => use iloc to retrieve data
    for i in range(0,4):
        if dt.month in working_day.keys():
            if dt.day < (month_eomonth[datetime(dt.year, dt.month, 1)] - 13):
                dm = round_up(df_demand_dnb.loc[df_demand_dnb.index[i],col] * 0.3 / ((working_day[dt.month]) - 12))
                df_daily_demand_dnb = df_daily_demand_dnb.append({'DATE':dt, 'THÀNH PHẨM':df_demand_dnb.index[i], 'MONTHLY_DEMAND_QTY':df_demand_dnb.loc[df_demand_dnb.index[i],col],'daily_demand':dm},ignore_index=True)
            if dt.day in range(month_eomonth[datetime(dt.year, dt.month, 1)] - 13, month_eomonth[datetime(dt.year, dt.month, 1)]+1):
                dm = round_up(df_demand_dnb.loc[df_demand_dnb.index[i],col] *  0.7 / 12)
                df_daily_demand_dnb = df_daily_demand_dnb.append({'DATE':dt, 'THÀNH PHẨM':df_demand_dnb.index[i],'MONTHLY_DEMAND_QTY':df_demand_dnb.loc[df_demand_dnb.index[i],col],'daily_demand':dm},ignore_index=True)
df_daily_demand_dnb.sort_values(by=['THÀNH PHẨM','DATE'],ignore_index=True, inplace=True)
# df_daily_demand_dnb = df_daily_demand_dnb.reset_index()
df_daily_demand_dnb

           THÀNH PHẨM  MONTHLY_DEMAND_QTY  daily_demand       DATE
0     STAR_SHEEP_25KG               124.0           2.9 2023-04-01
1     STAR_SHEEP_25KG               124.0           2.9 2023-04-03
2     STAR_SHEEP_25KG               124.0           2.9 2023-04-04
3     STAR_SHEEP_25KG               124.0           2.9 2023-04-05
4     STAR_SHEEP_25KG               124.0           2.9 2023-04-06
..                ...                 ...           ...        ...
307  WOW_CHICKEN_40KG               250.0          14.6 2023-06-26
308  WOW_CHICKEN_40KG               250.0          14.6 2023-06-27
309  WOW_CHICKEN_40KG               250.0          14.6 2023-06-28
310  WOW_CHICKEN_40KG               250.0          14.6 2023-06-29
311  WOW_CHICKEN_40KG               250.0          14.6 2023-06-30

[312 rows x 4 columns]

In [ ]:
df_daily_demand_dnb['purchasing_qty'] = 0
df_daily_demand_dnb['production_qty'] = 0

for ind, row in df_daily_demand_dnb.iterrows():
    if df_daily_demand_dnb['DATE'][ind].weekday() == 0:
        df_daily_demand_dnb['purchasing_qty'][ind] = df_daily_demand_dnb['daily_demand'][ind] * 2 + df_daily_demand_dnb['daily_demand'][ind+1] * 2 + df_daily_demand_dnb['daily_demand'][ind+2]       
        df_daily_demand_dnb['production_qty'][ind-1] = round_up(df_daily_demand_dnb['purchasing_qty'][ind] / 3)
        df_daily_demand_dnb['production_qty'][ind-2] = round_up(df_daily_demand_dnb['purchasing_qty'][ind] / 3)
        df_daily_demand_dnb['production_qty'][ind-3] = round_up(df_daily_demand_dnb['purchasing_qty'][ind] / 3)

    elif df_daily_demand_dnb['DATE'][ind].weekday() == 2:
        df_daily_demand_dnb['purchasing_qty'][ind] = df_daily_demand_dnb['daily_demand'][ind] * 2 + df_daily_demand_dnb['daily_demand'][ind+1] * 2 + df_daily_demand_dnb['daily_demand'][ind+2]       
        df_daily_demand_dnb['production_qty'][ind] = round_up(df_daily_demand_dnb['purchasing_qty'][ind] / 3)
        df_daily_demand_dnb['production_qty'][ind-1] = round_up(df_daily_demand_dnb['purchasing_qty'][ind] / 3)
        df_daily_demand_dnb['production_qty'][ind-2] = round_up(df_daily_demand_dnb['purchasing_qty'][ind] / 3)

print(df_daily_demand_dnb.head(10))

        THÀNH PHẨM  MONTHLY_DEMAND_QTY  daily_demand       DATE  \
0  STAR_SHEEP_25KG               124.0           2.9 2023-04-01
1  STAR_SHEEP_25KG               124.0           2.9 2023-04-03
2  STAR_SHEEP_25KG               124.0           2.9 2023-04-04
3  STAR_SHEEP_25KG               124.0           2.9 2023-04-05
4  STAR_SHEEP_25KG               124.0           2.9 2023-04-06
5  STAR_SHEEP_25KG               124.0           2.9 2023-04-07
6  STAR_SHEEP_25KG               124.0           2.9 2023-04-08
7  STAR_SHEEP_25KG               124.0           2.9 2023-04-10
8  STAR_SHEEP_25KG               124.0           2.9 2023-04-11
9  STAR_SHEEP_25KG               124.0           2.9 2023-04-12

   purchasing_qty  production_qty
0               0               4
1              14               4
2               0               4
3              14               4
4               0               4
5               0               4
6               0               4
7              14               4
8               0               4
9              14               4

In [ ]:
# DEMAND ĐÒNG BẰNG SÔNG CỬU LONG
# Select sheet Đồng bằng Sông Cửu Long
sheet_demand_dbscl = gc.open_by_url('https://docs.google.com/spreadsheets/d/16ABL8ArggCsUlfHr9Kx3hQElvmHi2yQUXBIhpS9O1aw/edit#gid=0').worksheet('Đồng bằng Sông Cửu Long')

# Select All columns
data = [e[0:] for e in sheet_demand_dbscl.get_all_values()] 

# Set first row of sheet as Dataframe column name
df_demand_dbscl = pd.DataFrame(data[0:], columns=data[0]) # Check
df_demand_dbscl = df_demand_dbscl.drop(df_demand_dbscl.index[0])
df_demand_dbscl['APR_2023'] = df_demand_dbscl['APR_2023'].astype('float64')
df_demand_dbscl['MAY_2023'] = df_demand_dbscl['MAY_2023'].astype('float64')
df_demand_dbscl['JUN_2023'] = df_demand_dbscl['JUN_2023'].astype('float64')

# SOH ĐÒNG BẰNG SÔNG CỬU LONG
df_soh_dnb = gc.open_by_url('https://docs.google.com/spreadsheets/d/1CbcVBSIXpGeFG_5BeN_o6Jna33WN0lWRCDP-6PBDa-A/edit#gid=0').worksheet('Đông Nam Bộ')
# Select All columns
data = [e[0:] for e in df_soh_dnb.get_all_values()] 
# Set first row of sheet as Dataframe column name
df_soh_dnb = pd.DataFrame(data[0:], columns=data[0]) # Check
df_soh_dnb = df_soh_dnb.drop(df_soh_dnb.index[0])
df_soh_dnb["TỒN KHO CUỐI NGÀY 31/3/2023"] = df_soh_dnb["TỒN KHO CUỐI NGÀY 31/3/2023"].astype('float64')

# production required - only change the demand of APR
# production required - only change the demand of APR
for ind, data in df_soh_dnb.iterrows():
  xx = df_soh_dnb.loc[ind,"ITEM"]
  if xx == "STAR_SHEEP_25KG":
    x = df_soh_dnb.loc[ind,"TỒN KHO CUỐI NGÀY 31/3/2023"]
    indd = df_demand_dbscl.loc[df_demand_dbscl["ITEM"] == "STAR_SHEEP_25KG"].index
    df_demand_dbscl.loc[indd,"APR_2023"] = df_demand_dbscl.loc[indd,"APR_2023"] - x
    df_soh_dnb = df_soh_dnb.drop(axis = 0, index = ind)
    continue
  if xx == "STAR_SHEEP_40KG":
    x = df_soh_dnb.loc[ind,"TỒN KHO CUỐI NGÀY 31/3/2023"]
    indd = df_demand_dbscl.loc[df_demand_dbscl["ITEM"] == "STAR_SHEEP_40KG"].index
    df_demand_dbscl.loc[indd,"APR_2023"] = df_demand_dbscl.loc[indd,"APR_2023"] - x
    df_soh_dnb = df_soh_dnb.drop(axis = 0, index = ind)
    continue
  if xx == "WOW_CHICKEN_25KG":
    x = df_soh_dnb.loc[ind,"TỒN KHO CUỐI NGÀY 31/3/2023"]
    indd = df_demand_dbscl.loc[df_demand_dbscl["ITEM"] == "WOW_CHICKEN_25KG"].index
    df_demand_dbscl.loc[indd,"APR_2023"] = df_demand_dbscl.loc[indd,"APR_2023"] - x
    df_soh_dnb = df_soh_dnb.drop(axis = 0, index = ind)
    continue
  if xx == "WOW_CHICKEN_40KG":
    x = df_soh_dnb.loc[ind,"TỒN KHO CUỐI NGÀY 31/3/2023"]
    indd = df_demand_dbscl.loc[df_demand_dbscl["ITEM"] == "WOW_CHICKEN_40KG"].index
    df_demand_dbscl.loc[indd,"APR_2023"] = df_demand_dbscl.loc[indd,"APR_2023"] - x
    df_soh_dnb = df_soh_dnb.drop(axis = 0, index = ind)
    continue

df_demand_dbscl = df_demand_dbscl.set_index('ITEM')
df_demand_dbscl

                  APR_2023  MAY_2023  JUN_2023
ITEM
STAR_SHEEP_25KG      224.0     450.0     500.0
STAR_SHEEP_40KG       90.0     300.0     250.0
WOW_CHICKEN_25KG    1138.0    1600.0    1800.0
WOW_CHICKEN_40KG     500.0     700.0    1100.0

In [ ]:
# tạo  1 empty df với col headings
df_daily_demand_dbscl = pd.DataFrame(columns=['DATE', 'THÀNH PHẨM', 'MONTHLY_DEMAND_QTY', 'daily_demand']) 
df_daily_demand_dbscl = df_daily_demand_dbscl.set_index('DATE')


# round up Daily_Demand to one decimal
def round_up(num):
    return math.ceil(num * 10) / 10

date_month = []
last_day = []

for d, l in month_eomonth.items():
    date_month.append(d.month)
    last_day.append(l)
    
month_n_last_day = {date_month[i]:last_day[i] for i in range(len(date_month))}

for ind,dt in enumerate(date_exclude_Sun):
    col = datetime.strftime(dt,'%b_%Y').upper() # chuyển datetime to str để so sánh => use iloc to retrieve data
    for i in range(0,4):
        if dt.month in working_day.keys():
            if dt.day < (month_eomonth[datetime(dt.year, dt.month, 1)] - 13):
                dm = round_up(df_demand_dbscl.loc[df_demand_dbscl.index[i],col] * 0.3 / ((working_day[dt.month]) - 12))
                df_daily_demand_dbscl = df_daily_demand_dbscl.append({'DATE':dt, 'THÀNH PHẨM':df_demand_dbscl.index[i], 'MONTHLY_DEMAND_QTY':df_demand_dbscl.loc[df_demand_dbscl.index[i],col],'daily_demand':dm},ignore_index=True)
            if dt.day in range(month_eomonth[datetime(dt.year, dt.month, 1)] - 13, month_eomonth[datetime(dt.year, dt.month, 1)]+1):
                dm = round_up(df_demand_dbscl.loc[df_demand_dbscl.index[i],col] *  0.7 / 12)
                df_daily_demand_dbscl = df_daily_demand_dbscl.append({'DATE':dt, 'THÀNH PHẨM':df_demand_dbscl.index[i],'MONTHLY_DEMAND_QTY':df_demand_dbscl.loc[df_demand_dbscl.index[i],col],'daily_demand':dm},ignore_index=True)
df_daily_demand_dbscl.sort_values(by=['THÀNH PHẨM','DATE'],ignore_index=True,inplace=True)
# df_daily_demand_dbscl.reset_index(inplace=True)
df_daily_demand_dbscl.head()

        THÀNH PHẨM  MONTHLY_DEMAND_QTY  daily_demand       DATE
0  STAR_SHEEP_25KG               224.0           5.2 2023-04-01
1  STAR_SHEEP_25KG               224.0           5.2 2023-04-03
2  STAR_SHEEP_25KG               224.0           5.2 2023-04-04
3  STAR_SHEEP_25KG               224.0           5.2 2023-04-05
4  STAR_SHEEP_25KG               224.0           5.2 2023-04-06

In [ ]:
df_daily_demand_dbscl['purchasing_qty'] = 0
df_daily_demand_dbscl['production_qty'] = 0

for ind, row in df_daily_demand_dbscl.iterrows():
    if df_daily_demand_dbscl.index[ind] <= 309:
        if df_daily_demand_dbscl['DATE'][ind].weekday() == 1:

            df_daily_demand_dbscl['purchasing_qty'][ind] = df_daily_demand_dbscl['daily_demand'][ind] * 2 + df_daily_demand_dbscl['daily_demand'][ind+1] * 2 + df_daily_demand_dbscl['daily_demand'][ind+2] * 2      
            df_daily_demand_dbscl['production_qty'][ind-2] = round_up(df_daily_demand_dbscl['purchasing_qty'][ind] / 3)
            df_daily_demand_dbscl['production_qty'][ind-3] = round_up(df_daily_demand_dbscl['purchasing_qty'][ind] / 3)
            df_daily_demand_dbscl['production_qty'][ind-4] = round_up(df_daily_demand_dbscl['purchasing_qty'][ind] / 3)

        elif df_daily_demand_dbscl['DATE'][ind].weekday() == 3:
            df_daily_demand_dbscl['purchasing_qty'][ind] = df_daily_demand_dbscl['daily_demand'][ind] * 2 + df_daily_demand_dbscl['daily_demand'][ind+1] * 2 + df_daily_demand_dbscl['daily_demand'][ind+2]  * 2     
            df_daily_demand_dbscl['production_qty'][ind-1] = round_up(df_daily_demand_dbscl['purchasing_qty'][ind] / 3)
            df_daily_demand_dbscl['production_qty'][ind-2] = round_up(df_daily_demand_dbscl['purchasing_qty'][ind] / 3)
            df_daily_demand_dbscl['production_qty'][ind-3] = round_up(df_daily_demand_dbscl['purchasing_qty'][ind] / 3)

df_daily_demand_dbscl.head()

,THÀNH PHẨM,MONTHLY_DEMAND_QTY,daily_demand,DATE,purchasing_qty,production_qty
0,STAR_SHEEP_25KG,224.0,5.2,2023-04-01,0,10
1,STAR_SHEEP_25KG,224.0,5.2,2023-04-03,0,10
2,STAR_SHEEP_25KG,224.0,5.2,2023-04-04,31,10
3,STAR_SHEEP_25KG,224.0,5.2,2023-04-05,0,10
4,STAR_SHEEP_25KG,224.0,5.2,2023-04-06,31,10

In [ ]:
writer = pd.ExcelWriter('production_planning.xlsx', mode='w', engine='openpyxl')
df_daily_demand_dnb.to_excel(writer, sheet_name='production_planning_dnb',index=False, freeze_panes=(1,1))
df_daily_demand_dbscl.to_excel(writer, sheet_name='production_planning_dbscl',index=False, freeze_panes=(1,1))
writer.save()

In [ ]:
import pandas as pd
from sqlalchemy import create_engine

import calendar
import math 
import numpy
import datetime

In [ ]:
# Khai báo credential
str_user = 'user_schf'
str_password = '11223344'
str_db = 'db_schf_round3'

In [ ]:
# Tạo connection
engine = create_engine(
    f"postgresql://{str_user}:{str_password }@139.180.184.67:5432/{str_db}?sslmode=require"
)
connection = engine.connect()

In [ ]:
# Đọc bảng INPUT_BOM
df_bom = pd.read_sql("""select * from INPUT_BOM""",con=connection)
df_bom.head()

,THÀNH PHẨM,NGUYÊN LIỆU,SỐ LƯỢNG NGUYÊN LIỆU TRÊN 1 THÀNH PHẨM,ĐƠN VỊ
0,STAR_SHEEP_25KG,NGÔ,6.250,kg
1,STAR_SHEEP_25KG,KHOAI,12.500,kg
2,STAR_SHEEP_25KG,SẮN,3.125,kg
3,STAR_SHEEP_25KG,XƯƠNG_ĐỘNG_VẬT,3.125,kg
4,STAR_SHEEP_25KG,MEN_VI_SINH,0.625,lít

In [ ]:
# Đọc bảng INPUT_ITEMMASTER
df_imr = pd.read_sql("""select * from INPUT_ITEMMASTER""",con=connection)
df_imr.rename(columns={"ITEM":"NGUYÊN LIỆU"},inplace=True)
#MOQ của sản phẩm bao bì được cho là 1000 mỗi sản phẩm
df_imr.loc[8,"MOQ"]=1000
#SHELF-LIFE của nguyên liệu (được tính tính tay từ input đề)
df_imr['SHELF LIFE ĐƯỢC ƯỚC TÍNH KỂ TỪ NGÀY NHẬP KHO (NGÀY)']=[74,104,104,104,104,34,34,366,366]
#SHELF-LIFE của nguyên liệu được tính lại còn 1 nửa, do quá 50% thì không được phép đưa vào SX
df_imr['SHELF LIFE ĐƯỢC ƯỚC TÍNH KỂ TỪ NGÀY NHẬP KHO (NGÀY)'] = df_imr['SHELF LIFE ĐƯỢC ƯỚC TÍNH KỂ TỪ NGÀY NHẬP KHO (NGÀY)']/2 #quá 50% k cho vào sx
#Leadtime từ 7 ngày lên 8. vì trong 1 tuần chắc chắn dính 1 ngày CN (không làm việc);
df_imr['LEADTIME ĐẶT HÀNG (NGÀY)'] = df_imr['LEADTIME ĐẶT HÀNG (NGÀY)']+1
df_imr.head()

,NGUYÊN LIỆU,LOẠI,NHÀ CUNG CẤP,LEADTIME ĐẶT HÀNG (NGÀY),MOQ,ĐƠN VỊ,SHELF LIFE ĐƯỢC ƯỚC TÍNH KỂ TỪ NGÀY NHẬP KHO (NGÀY)
0,KHOAI,Nguyên liệu,CÔNG TY TNHH NARGI,8,3000.0,kg,37.0
1,SẮN,Nguyên liệu,CÔNG TY TNHH NARGI,8,1500.0,kg,52.0
2,NGÔ,Nguyên liệu,CÔNG TY TNHH NARGI,8,3000.0,kg,52.0
3,BỘT_ĐỖ_TƯƠNG,Nguyên liệu,CÔNG TY TNHH NARGI,8,1500.0,kg,52.0
4,THÓC,Nguyên liệu,CÔNG TY TNHH NARGI,8,3000.0,kg,52.0

In [ ]:
#Đọc file Demand, production plan
# DEMAND ĐÔNG NAM BỘ
# Select sheet Đông Nam Bộ
sheet_demand_dnb = gc.open_by_url('https://docs.google.com/spreadsheets/d/16ABL8ArggCsUlfHr9Kx3hQElvmHi2yQUXBIhpS9O1aw/edit#gid=0').worksheet('Đông Nam Bộ')

# Select All columns
data = [e[0:] for e in sheet_demand_dnb.get_all_values()] 

# Set first row of sheet as Dataframe column name
df_demand_dnb = pd.DataFrame(data[0:], columns=data[0]) # Check

# df_production_dnb = pd.read_excel("production_planning.xlsx", sheet_name = "production_planning_dnb")
# df_production_dbscl = pd.read_excel("production_planning.xlsx", sheet_name = "production_planning_dbscl")
df_production = pd.concat([df_daily_demand_dnb,df_daily_demand_dbscl],ignore_index = True)
print(df_production["DATE"])

#Đọc file Supply On hand & On Going do nhóm đã tạo bản sao từ INPUT gốc và thêm vào sheet On-going
df_soh = pd.read_excel("https://docs.google.com/spreadsheets/d/1PUpjIty_uhfirXfIKNucXMrcxt26GX0IF_xLi8CZLck/export", sheet_name = "Nhà máy")
df_sog = pd.read_excel("https://docs.google.com/spreadsheets/d/1PUpjIty_uhfirXfIKNucXMrcxt26GX0IF_xLi8CZLck/export", sheet_name = "On-going")

#CHUẨN HÓA TÊN CÁC CỘT INPUT 
df_soh.rename(columns={"ITEM":"NGUYÊN LIỆU","TỒN KHO CUỐI NGÀY 31/3/2023":"TỒN KHO CUỐI NGÀY","HẠN SỬ DỤNG TRÊN BAO BÌ":"HẠN SỬ DỤNG"},inplace=True)
df_sog.rename(columns={"ITEM":"NGUYÊN LIỆU"},inplace=True)

#SETUP FILE ĐÁP ÁN 
df_expired = pd.DataFrame(columns=["NGÀY HẾT HẠN","NGUYÊN LIỆU", "SỐ LƯỢNG","ĐƠN VỊ"])
df_expired["SỐ LƯỢNG"] = df_expired["SỐ LƯỢNG"].astype(float)
df_order = pd.DataFrame(columns=["NGÀY ĐẶT","NGUYÊN LIỆU","NHÀ CUNG CẤP", "SỐ LƯỢNG"])

0     2023-04-01
1     2023-04-03
2     2023-04-04
3     2023-04-05
4     2023-04-06
         ...
619   2023-06-26
620   2023-06-27
621   2023-06-28
622   2023-06-29
623   2023-06-30
Name: DATE, Length: 624, dtype: datetime64[ns]

In [ ]:
#THAM KHẢO CASE FIFO, THÊM YẾU TỐ SAFETY STOCK
from datetime import datetime, timedelta
def xu_ly_SL_CONLAI(df_in):
  from datetime import datetime, timedelta
  global df_soh
  global df_imr
  global df_order
  global df_sog
  global dd 
  global safety_stock
  max_ind = df_in['THIẾU'].lt(0).idxmax() #10
  df_soh.loc[max_ind,'TỒN KHO CUỐI NGÀY'] = - (df_in.loc[max_ind,'THIẾU'])
  for ind, data in df_in.iterrows():
    
    qty_thieu = df_in.loc[ind,'THIẾU']

    #Nếu SL thiếu >= 0  ===> Lấy hết => Stock về 0 
    if qty_thieu >=0:
      df_soh.loc[ind, "TỒN KHO CUỐI NGÀY"]=0
  
  #Nếu xảy ra tình trạng hết hàng giữa chừng, ta tiến hành đặt bổ sung trong tháng 
  if qty_thieu > 0 :
    x = df_in.loc[ind,"NGUYÊN LIỆU"]
    ind = df_imr["NGUYÊN LIỆU"].eq(x).idxmax()
    moq = df_imr.loc[ind,"MOQ"]
    order = qty_thieu            
    rorder = math.ceil(order/moq)
    from datetime import datetime, timedelta
    df_imr["SHELF LIFE ĐƯỢC ƯỚC TÍNH KỂ TỪ NGÀY NHẬP KHO (NGÀY)"] = df_imr["SHELF LIFE ĐƯỢC ƯỚC TÍNH KỂ TỪ NGÀY NHẬP KHO (NGÀY)"].astype(float)
    HSD = dd + timedelta(days=df_imr.loc[ind,'SHELF LIFE ĐƯỢC ƯỚC TÍNH KỂ TỪ NGÀY NHẬP KHO (NGÀY)'])
    df_sog = df_sog.append({"NGUYÊN LIỆU":x,"SỐ LƯỢNG":rorder*moq-qty_thieu, "NGÀY VỀ":dd,"ĐƠN VỊ":df_imr.loc[ind,"ĐƠN VỊ"], "HẠN SỬ DỤNG":HSD},ignore_index=True)  
    df_imr["LEADTIME ĐẶT HÀNG (NGÀY)"] = df_imr["LEADTIME ĐẶT HÀNG (NGÀY)"].astype(float)
    df_order = df_order.append({"NGUYÊN LIỆU":x,"NHÀ CUNG CẤP":df_imr.loc[ind,"NHÀ CUNG CẤP"], "SỐ LƯỢNG":rorder, 
                     "NGÀY ĐẶT": dd - timedelta(days=df_imr.loc[ind,"LEADTIME ĐẶT HÀNG (NGÀY)"])}, ignore_index=True)
    exit
  
  #Lượng tồn kho trong kho tuột xuống dưới safety_stock cho 10 ngày --> tiến hành đặt bù 
  ind = df_in['inv_cumsum'].idxmax()
  if df_in.loc[ind, 'inv_cumsum'] < df_in.loc[ind, "NHU CẦU NGUYÊN LIỆU"]*10:
    order = df_in.loc[ind, "NHU CẦU NGUYÊN LIỆU"]*10 - df_in.loc[ind, 'inv_cumsum']       
    x = df_in.loc[ind,"NGUYÊN LIỆU"]
    ind = df_imr["NGUYÊN LIỆU"].eq(x).idxmax()
    moq = df_imr.loc[ind,"MOQ"]
    rorder = math.ceil(order/moq)
    df_imr["SHELF LIFE ĐƯỢC ƯỚC TÍNH KỂ TỪ NGÀY NHẬP KHO (NGÀY)"] = df_imr["SHELF LIFE ĐƯỢC ƯỚC TÍNH KỂ TỪ NGÀY NHẬP KHO (NGÀY)"].astype(float)
    HSD = dd + timedelta(days=df_imr.loc[ind,'SHELF LIFE ĐƯỢC ƯỚC TÍNH KỂ TỪ NGÀY NHẬP KHO (NGÀY)'])
    df_sog = df_sog.append({"NGUYÊN LIỆU":x,"SỐ LƯỢNG":rorder*moq-qty_thieu, "NGÀY VỀ":dd,"ĐƠN VỊ":df_imr.loc[ind,"ĐƠN VỊ"], "HẠN SỬ DỤNG":HSD},ignore_index=True)  
    df_imr["LEADTIME ĐẶT HÀNG (NGÀY)"] = df_imr["LEADTIME ĐẶT HÀNG (NGÀY)"].astype(float)
    df_order = df_order.append({"NGUYÊN LIỆU":x,"NHÀ CUNG CẤP":df_imr.loc[ind,"NHÀ CUNG CẤP"], "SỐ LƯỢNG":rorder, 
                     "NGÀY ĐẶT": dd - timedelta(days=df_imr.loc[ind,"LEADTIME ĐẶT HÀNG (NGÀY)"])}, ignore_index=True)
    exit
          
def day_by_day(df_in):
    from datetime import datetime, timedelta
    global df_soh
    global df_sog
    global df_bom
    global df_imr
    global df_order
    global df_expired
    global dd 
      
    df_sohh=pd.DataFrame()
    #gán mốc là ngày trong file  
    df_in = df_in.reset_index()
    dd = df_in.loc[0,"DATE"]
    #Nếu đây là đầu tháng
    if dd.day == 1:
        df_ofm = df_in.merge(df_bom, on = "THÀNH PHẨM", how = 'inner')
        df_ofm['MONTHLY_DEMAND_QTY']= df_ofm['MONTHLY_DEMAND_QTY'].astype(float)
        df_ofm['LƯỢNG NGUYÊN LIỆU CẦN']=df_ofm["MONTHLY_DEMAND_QTY"]*df_ofm["SỐ LƯỢNG NGUYÊN LIỆU TRÊN 1 THÀNH PHẨM"]*1.3
        df_ofm = df_ofm.groupby("NGUYÊN LIỆU").sum()
        df_sohh = df_soh.groupby("NGUYÊN LIỆU")["TỒN KHO CUỐI NGÀY"].sum()
        df_ofm = df_ofm.merge(df_sohh,on="NGUYÊN LIỆU",how='inner')
        df_ofm['CẦN ĐẶT']=df_ofm['LƯỢNG NGUYÊN LIỆU CẦN']- df_ofm['TỒN KHO CUỐI NGÀY']
        df_ofm=df_ofm.merge(df_imr,on = "NGUYÊN LIỆU", how = 'inner')
        df_ofm["LEADTIME ĐẶT HÀNG (NGÀY)"] = df_ofm["LEADTIME ĐẶT HÀNG (NGÀY)"].astype(float)
        df_ofm["SHELF LIFE ĐƯỢC ƯỚC TÍNH KỂ TỪ NGÀY NHẬP KHO (NGÀY)"] = df_ofm["SHELF LIFE ĐƯỢC ƯỚC TÍNH KỂ TỪ NGÀY NHẬP KHO (NGÀY)"].astype(float)
        for ind, data in df_ofm.iterrows():
            if df_ofm.loc[ind,"CẦN ĐẶT"] > 0:
                df_ofm.loc[ind,"ĐẶT THỰC TẾ"] = math.ceil(df_ofm.loc[ind,"CẦN ĐẶT"]/df_ofm.loc[ind,"MOQ"])

                df_sog = df_sog.append({"NGUYÊN LIỆU":df_ofm.loc[ind,"NGUYÊN LIỆU"],
                                            "SỐ LƯỢNG":df_ofm.loc[ind,"MOQ"]*df_ofm.loc[ind,"ĐẶT THỰC TẾ"],
                                            "NGÀY VỀ":dd,
                                            "HẠN SỬ DỤNG":dd + timedelta(days=df_ofm.loc[ind,"SHELF LIFE ĐƯỢC ƯỚC TÍNH KỂ TỪ NGÀY NHẬP KHO (NGÀY)"])
                                            ,"ĐƠN VỊ":df_ofm.loc[ind,"ĐƠN VỊ"]},ignore_index=True)
                df_order = df_order.append({"NGUYÊN LIỆU":df_ofm.loc[ind,"NGUYÊN LIỆU"],
                                            "NHÀ CUNG CẤP":df_ofm.loc[ind,"NHÀ CUNG CẤP"],
                                            "SỐ LƯỢNG":df_ofm.loc[ind,"ĐẶT THỰC TẾ"],
                                            "NGÀY ĐẶT": dd - timedelta(days=df_ofm.loc[ind,"LEADTIME ĐẶT HÀNG (NGÀY)"])}, ignore_index=True)
      
            else:
                df_ofm.loc[ind,"ĐẶT THỰC TẾ"] = 0
    
    # Kiểm tra hết hạn
    for ind, data in df_soh.iterrows():
        if df_soh.loc[ind,"HẠN SỬ DỤNG"] <= dd:
            # print(df_soh)
            df_soh["TỒN KHO CUỐI NGÀY"].fillna(0,inplace=True)
            df_soh["TỒN KHO CUỐI NGÀY"] = df_soh["TỒN KHO CUỐI NGÀY"].astype(int)
            if  df_soh.loc[ind,"TỒN KHO CUỐI NGÀY"] > 0:  #Hết hạn mà còn tồn kho thì phải HỦY HÀNG
              df_expired = df_expired.append({"NGUYÊN LIỆU":df_soh.loc[ind,"NGUYÊN LIỆU"], "SỐ LƯỢNG": df_soh.loc[ind,"TỒN KHO CUỐI NGÀY"],"ĐƠN VỊ":df_soh.loc[ind,"ĐƠN VỊ"], "NGÀY HẾT HẠN":df_soh.loc[ind,"HẠN SỬ DỤNG"]},ignore_index=True)
            df_soh.loc[ind,"TỒN KHO CUỐI NGÀY"]=0
             
    # Kiểm tra hàng đang về ==> Nếu có đưa qua bảng On-Hand stock
    for ind, data in df_sog.iterrows():
        df_sohh = df_soh
        if df_sog.loc[ind,"NGÀY VỀ"] <= dd: 
            df_soh = df_soh.append({"NGUYÊN LIỆU":df_sog.loc[ind,"NGUYÊN LIỆU"], "TỒN KHO CUỐI NGÀY": df_sog.loc[ind,"SỐ LƯỢNG"],"ĐƠN VỊ":df_sog.loc[ind,"ĐƠN VỊ"], "HẠN SỬ DỤNG":df_sog.loc[ind,"HẠN SỬ DỤNG"]},ignore_index=True)
            df_sohh=df_soh
            df_sog = df_sog.drop(axis = 0, index = ind)
        df_soh = df_sohh
    #Cập nhật tồn kho sau 1 ngày "lao động hăng say"
    df_merge = df_in.merge(df_bom,on = "THÀNH PHẨM", how = 'inner')
    df_merge["NHU CẦU NGUYÊN LIỆU"]=df_merge["SỐ LƯỢNG NGUYÊN LIỆU TRÊN 1 THÀNH PHẨM"]*df_merge["production_qty"]
    df_merge = df_merge.groupby("NGUYÊN LIỆU").sum()
    df_merge = df_soh.merge(df_merge,on="NGUYÊN LIỆU",how = "left")
    df_merge.sort_values(by=["NGUYÊN LIỆU","HẠN SỬ DỤNG"],inplace=True)
    df_merge['inv_cumsum'] = df_merge.groupby("NGUYÊN LIỆU")['TỒN KHO CUỐI NGÀY'].cumsum()
    df_merge['THIẾU'] = df_merge['NHU CẦU NGUYÊN LIỆU'] - df_merge['inv_cumsum']
    df_merge.groupby('NGUYÊN LIỆU').apply(xu_ly_SL_CONLAI)

In [ ]:
#Production cần tính lại do hao hụt 2% trong sản xuất
df_production["production_qty"] = df_production["production_qty"]/0.98

#Clear lượng thành phẩm còn trong kho, nếu thành phẩm còn thì không cần phải sản xuất --> production_qty = 0
for ind, data in df_soh.iterrows():
  xx = df_soh.loc[ind,"NGUYÊN LIỆU"]
  if xx == "STAR_SHEEP_25KG":
    x = df_soh.loc[ind,"TỒN KHO CUỐI NGÀY"]
    indd = df_production.loc[df_production["THÀNH PHẨM"] == "STAR_SHEEP_25KG"].index
    for i in indd:
      df_production.loc[i,"production_qty"] = max(0,df_production.loc[i,"production_qty"]-x)
      x = x - df_production.loc[i,"production_qty"]
      if x <=0: 
        continue
    df_soh = df_soh.drop(axis = 0, index = ind)
  if xx == "STAR_SHEEP_40KG":
    x = df_soh.loc[ind,"TỒN KHO CUỐI NGÀY"]
    indd = df_production.loc[df_production["THÀNH PHẨM"] == "STAR_SHEEP_40KG"].index
    for i in indd:
      df_production.loc[i,"production_qty"] = max(0,df_production.loc[i,"production_qty"]-x)
      x = x - df_production.loc[i,"production_qty"]
      if x <=0: 
        continue
    df_soh = df_soh.drop(axis = 0, index = ind)
  if xx == "WOW_CHICKEN_25KG":
    x = df_soh.loc[ind,"TỒN KHO CUỐI NGÀY"]
    indd = df_production.loc[df_production["THÀNH PHẨM"] == "STAR_SHEEP_25KG"].index
    for i in indd:
      df_production.loc[i,"production_qty"] = max(0,df_production.loc[i,"production_qty"]-x)
      x = x - df_production.loc[i,"production_qty"]
      if x <=0: 
        continue
    df_soh = df_soh.drop(axis = 0, index = ind)
  if xx == "WOW_CHICKEN_40KG":
    x = df_soh.loc[ind,"TỒN KHO CUỐI NGÀY"]
    indd = df_production.loc[df_production["THÀNH PHẨM"] == "STAR_SHEEP_25KG"].index
    for i in indd:
      df_production.loc[i,"production_qty"] = max(0,df_production.loc[i,"production_qty"]-x)
      x = x - df_production.loc[i,"production_qty"]
      if x <=0: 
        continue
    df_soh = df_soh.drop(axis = 0, index = ind)

#CHƯƠNG TRÌNH CHÍNH, HOẠCH ĐỊNH ĐẶT HÀNG THEO TỪNG NGÀY SX CỦA NHÀ MÁY
df_production.groupby("DATE").apply(day_by_day)

#XUẤT CÁC FILE ĐÁP ÁN 
df_order.sort_values(by=["NGÀY ĐẶT"],inplace=True,ignore_index=True)
print(df_order)
df_order.to_excel("KẾ HOẠCH ĐẶT HÀNG.xlsx")
print("-----")

df_expired["SỐ LƯỢNG"] = df_expired["SỐ LƯỢNG"].astype(int)
print(df_expired)
df_expired.to_excel("HÀNG HẾT HẠN.xlsx")

     NGÀY ĐẶT     NGUYÊN LIỆU         NHÀ CUNG CẤP  SỐ LƯỢNG
0  2023-03-24     BAO_BÌ_25KG  CÔNG TY TNHH WOPACK       2.0
1  2023-03-24     BAO_BÌ_40KG  CÔNG TY TNHH WOPACK       1.0
2  2023-03-24    BỘT_ĐỖ_TƯƠNG   CÔNG TY TNHH NARGI       6.0
3  2023-03-24           KHOAI   CÔNG TY TNHH NARGI       2.0
4  2023-03-24             NGÔ   CÔNG TY TNHH NARGI       6.0
5  2023-03-24             SẮN   CÔNG TY TNHH NARGI       1.0
6  2023-03-24            THÓC   CÔNG TY TNHH NARGI      12.0
7  2023-03-24  XƯƠNG_ĐỘNG_VẬT     CÔNG TY CP YFOOD       8.0
8  2023-03-29     MEN_VI_SINH       CÔNG TY VNIBIO      18.0
9  2023-04-05            THÓC   CÔNG TY TNHH NARGI       2.0
10 2023-04-06    BỘT_ĐỖ_TƯƠNG   CÔNG TY TNHH NARGI       1.0
11 2023-04-06             NGÔ   CÔNG TY TNHH NARGI       1.0
12 2023-04-06  XƯƠNG_ĐỘNG_VẬT     CÔNG TY CP YFOOD       1.0
13 2023-04-11     MEN_VI_SINH       CÔNG TY VNIBIO       1.0
14 2023-04-16     BAO_BÌ_25KG  CÔNG TY TNHH WOPACK       1.0
15 2023-04-16            THÓC   CÔNG TY TNHH NARGI       1.0
16 2023-04-17     BAO_BÌ_40KG  CÔNG TY TNHH WOPACK       1.0
17 2023-04-17  XƯƠNG_ĐỘNG_VẬT     CÔNG TY CP YFOOD       1.0
18 2023-04-18    BỘT_ĐỖ_TƯƠNG   CÔNG TY TNHH NARGI       1.0
19 2023-04-19     MEN_VI_SINH       CÔNG TY VNIBIO       1.0
20 2023-04-23     BAO_BÌ_25KG  CÔNG TY TNHH WOPACK       1.0
21 2023-04-23    BỘT_ĐỖ_TƯƠNG   CÔNG TY TNHH NARGI       1.0
22 2023-04-23           KHOAI   CÔNG TY TNHH NARGI       5.0
23 2023-04-23             NGÔ   CÔNG TY TNHH NARGI      10.0
24 2023-04-23             SẮN   CÔNG TY TNHH NARGI       3.0
25 2023-04-23            THÓC   CÔNG TY TNHH NARGI       3.0
26 2023-04-23  XƯƠNG_ĐỘNG_VẬT     CÔNG TY CP YFOOD       8.0
27 2023-04-28     MEN_VI_SINH       CÔNG TY VNIBIO      20.0
28 2023-05-07  XƯƠNG_ĐỘNG_VẬT     CÔNG TY CP YFOOD       6.0
29 2023-05-07            THÓC   CÔNG TY TNHH NARGI       4.0
30 2023-05-07    BỘT_ĐỖ_TƯƠNG   CÔNG TY TNHH NARGI       2.0
31 2023-05-10     BAO_BÌ_25KG  CÔNG TY TNHH WOPACK       1.0
32 2023-05-10             NGÔ   CÔNG TY TNHH NARGI       1.0
33 2023-05-10  XƯƠNG_ĐỘNG_VẬT     CÔNG TY CP YFOOD       2.0
34 2023-05-12     BAO_BÌ_40KG  CÔNG TY TNHH WOPACK       1.0
35 2023-05-12     MEN_VI_SINH       CÔNG TY VNIBIO      11.0
36 2023-05-15     MEN_VI_SINH       CÔNG TY VNIBIO       4.0
37 2023-05-15            THÓC   CÔNG TY TNHH NARGI       1.0
38 2023-05-16    BỘT_ĐỖ_TƯƠNG   CÔNG TY TNHH NARGI       1.0
39 2023-05-24             NGÔ   CÔNG TY TNHH NARGI      10.0
40 2023-05-24  XƯƠNG_ĐỘNG_VẬT     CÔNG TY CP YFOOD      16.0
41 2023-05-24            THÓC   CÔNG TY TNHH NARGI       5.0
42 2023-05-24           KHOAI   CÔNG TY TNHH NARGI       2.0
43 2023-05-24    BỘT_ĐỖ_TƯƠNG   CÔNG TY TNHH NARGI       2.0
44 2023-05-24     BAO_BÌ_40KG  CÔNG TY TNHH WOPACK       1.0
45 2023-05-24     BAO_BÌ_25KG  CÔNG TY TNHH WOPACK       2.0
46 2023-05-29     MEN_VI_SINH       CÔNG TY VNIBIO      33.0
47 2023-06-07    BỘT_ĐỖ_TƯƠNG   CÔNG TY TNHH NARGI       3.0
48 2023-06-07            THÓC   CÔNG TY TNHH NARGI       8.0
49 2023-06-07  XƯƠNG_ĐỘNG_VẬT     CÔNG TY CP YFOOD       8.0
50 2023-06-08             NGÔ   CÔNG TY TNHH NARGI       1.0
51 2023-06-09     BAO_BÌ_25KG  CÔNG TY TNHH WOPACK       1.0
52 2023-06-11  XƯƠNG_ĐỘNG_VẬT     CÔNG TY CP YFOOD       2.0
53 2023-06-12     MEN_VI_SINH       CÔNG TY VNIBIO      15.0
54 2023-06-13     BAO_BÌ_40KG  CÔNG TY TNHH WOPACK       1.0
55 2023-06-15    BỘT_ĐỖ_TƯƠNG   CÔNG TY TNHH NARGI       1.0
56 2023-06-15            THÓC   CÔNG TY TNHH NARGI       2.0
57 2023-06-16     MEN_VI_SINH       CÔNG TY VNIBIO       3.0
-----
   NGÀY HẾT HẠN     NGUYÊN LIỆU  SỐ LƯỢNG ĐƠN VỊ
0    2023-04-18     MEN_VI_SINH       367    lít
1    2023-04-18  XƯƠNG_ĐỘNG_VẬT       835     kg
2    2023-05-01     MEN_VI_SINH        39    lít
3    2023-05-01  XƯƠNG_ĐỘNG_VẬT      5503     kg
4    2023-05-04     MEN_VI_SINH       454    lít
5    2023-05-08           KHOAI      6000     kg
6    2023-05-09     MEN_VI_SINH      1315    lít
7    2023-05-12  XƯƠNG_ĐỘNG_VẬT      4028     kg
8    2023-05-18     MEN_VI_SINH       672    lít
9    2023-05-18  XƯƠNG_ĐỘNG_VẬT      2954     kg
10   2023-05-23             SẮN      1500     kg
11   2023-06-04     MEN_VI_SINH      1593    lít
12   2023-06-04  XƯƠNG_ĐỘNG_VẬT      8194     kg
13   2023-06-07           KHOAI     15000     kg
14   2023-06-14             SẮN      1999     kg
15   2023-06-18     MEN_VI_SINH       975    lít
16   2023-06-18  XƯƠNG_ĐỘNG_VẬT      4402     kg
17   2023-06-21           KHOAI      7195     kg
18   2023-06-22             SẮN      4500     kg